import { pgTable, text, serial, integer, boolean, timestamp, real, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  username: text("username").unique(),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  firstName: text("first_name"),
  lastName: text("last_name"),
  profileImageUrl: text("profile_image_url"),
  age: integer("age"),
  height: real("height"), // in cm
  weight: real("weight"), // in kg
  gender: text("gender"), // 'male' | 'female'
  activityLevel: text("activity_level"), // 'sedentary' | 'light' | 'moderate' | 'active' | 'very-active'
  fitnessGoal: text("fitness_goal"), // 'weight-loss' | 'muscle-gain' | 'endurance' | 'strength' | 'general-fitness'
  dailyCalorieGoal: integer("daily_calorie_goal"),
  role: text("role").default("user").notNull(), // 'admin' | 'user'
  lastLoginAt: timestamp("last_login_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const exercises = pgTable("exercises", {
  id: serial("id").primaryKey(),
  exerciseId: text("exercise_id").notNull().unique(), // From ExerciseDB API
  name: text("name").notNull(),
  bodyPart: text("body_part").notNull(),
  target: text("target").notNull(),
  equipment: text("equipment").notNull(),
  gifUrl: text("gif_url"),
  instructions: text("instructions").array(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const workoutPlans = pgTable("workout_plans", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => users.id).notNull(),
  title: text("title").notNull(),
  description: text("description"),
  goal: text("goal").notNull(),
  experienceLevel: text("experience_level").notNull(),
  daysPerWeek: integer("days_per_week").notNull(),
  sessionDuration: integer("session_duration").notNull(), // in minutes
  planData: jsonb("plan_data").notNull(), // Generated by AI
  isActive: boolean("is_active").default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const workoutSessions = pgTable("workout_sessions", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => users.id).notNull(),
  planId: integer("plan_id").references(() => workoutPlans.id),
  date: timestamp("date").notNull(),
  exercises: jsonb("exercises").notNull(), // Array of exercises with sets/reps
  completed: boolean("completed").default(false),
  duration: integer("duration"), // actual duration in minutes
  notes: text("notes"),
});

export const foodEntries = pgTable("food_entries", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => users.id).notNull(),
  date: timestamp("date").notNull(),
  meal: text("meal").notNull(), // 'breakfast' | 'lunch' | 'dinner' | 'snack'
  foodName: text("food_name").notNull(),
  serving: text("serving").notNull(),
  calories: integer("calories").notNull(),
  protein: real("protein"), // in grams
  carbs: real("carbs"), // in grams
  fat: real("fat"), // in grams
});

// Workout Tracker - Individual workout sessions with multiple exercises
export const workoutTrackerSessions = pgTable("workout_tracker_sessions", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => users.id).notNull(),
  date: timestamp("date").defaultNow().notNull(),
  workoutName: text("workout_name").notNull(),
  exercises: jsonb("exercises").notNull(), // Array of exercises with name, sets, reps
  totalDuration: integer("total_duration"), // in minutes
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Weight Tracking for goal progress
export const weightEntries = pgTable("weight_entries", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => users.id).notNull(),
  weight: real("weight").notNull(), // in kg or lbs
  date: timestamp("date").defaultNow().notNull(),
  goalWeight: real("goal_weight"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});



// Insert schemas
export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  lastLoginAt: true,
});

export const insertExerciseSchema = createInsertSchema(exercises).omit({
  id: true,
});

export const insertWorkoutPlanSchema = createInsertSchema(workoutPlans).omit({
  id: true,
  createdAt: true,
});

export const insertWorkoutSessionSchema = createInsertSchema(workoutSessions).omit({
  id: true,
});

export const insertFoodEntrySchema = createInsertSchema(foodEntries).omit({
  id: true,
}).extend({
  date: z.coerce.date()
});

export const insertWorkoutTrackerSessionSchema = createInsertSchema(workoutTrackerSessions).omit({
  id: true,
  createdAt: true,
}).extend({
  date: z.coerce.date()
});

export const insertWeightEntrySchema = createInsertSchema(weightEntries).omit({
  id: true,
  createdAt: true,
}).extend({
  date: z.coerce.date()
});

// Types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Exercise = typeof exercises.$inferSelect;
export type InsertExercise = z.infer<typeof insertExerciseSchema>;
export type WorkoutPlan = typeof workoutPlans.$inferSelect;
export type InsertWorkoutPlan = z.infer<typeof insertWorkoutPlanSchema>;
export type WorkoutSession = typeof workoutSessions.$inferSelect;
export type InsertWorkoutSession = z.infer<typeof insertWorkoutSessionSchema>;
export type WorkoutTrackerSession = typeof workoutTrackerSessions.$inferSelect;
export type InsertWorkoutTrackerSession = z.infer<typeof insertWorkoutTrackerSessionSchema>;
export type WeightEntry = typeof weightEntries.$inferSelect;
export type InsertWeightEntry = z.infer<typeof insertWeightEntrySchema>;
export type FoodEntry = typeof foodEntries.$inferSelect;
export type InsertFoodEntry = z.infer<typeof insertFoodEntrySchema>;
